/*      File Name                Flash Index                   */
/*      ---------                -----------                   */
#define Page_1_preCache            0x20  /* File Size = 0xA0   */
#define Page_1                     0x21  /* File Size = 0x134  */
/*      Servo_channel_63x238.png   0x22  /* File Size = 0x3D2  */
/*      Servo_handle.png           0x23  /* File Size = 0x12F6 */
/*      Arial_24.auf               0x24  /* File Size = 0xBFC2 */
/*      fonthdr.auf                0xF   /* File Size = 0x3E   */
/*      internalram.bin            0x6   /* File Size = 0x2138 */
/*      sdramconfig.bin            0x1   /* File Size = 0x92   */
/*      rttinit.bin                0x1D  /* File Size = 0x12   */
